# Generated by Django 4.1.13 on 2024-02-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('allows_advertising', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('program', models.CharField(max_length=500)),
                ('conductor', models.CharField(max_length=50)),
                ('max_number_tickets', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('reference_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('number_discount', models.PositiveIntegerField(default=0)),
                ('number_regular', models.PositiveIntegerField(default=0)),
                ('delete_code', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('warning_sent', models.BooleanField(default=False)),
                ('warning_date', models.DateTimeField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_code', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('REGULAR', 'Vollpreis'), ('DISCOUNT', 'Ermäßigt')], max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.order')),
            ],
        ),
    ]
